# Generated by Django 5.1.7 on 2025-03-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('romaji', models.CharField(blank=True, max_length=20, null=True)),
                ('meaning', models.CharField(blank=True, max_length=100, null=True)),
                ('example_word', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='character_audio/')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='languages.languagescript')),
            ],
        ),
    ]
