# Generated by Django 5.1.7 on 2025-04-05 15:25

import manabhi_dojo.languages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(db_index=True, max_length=5, unique=True)),
                ('onyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('kunyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('jlpt_level', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='kanji_audio/')),
                ('image', models.ImageField(null=True, upload_to='kanji/')),
            ],
            options={
                'db_table': 'kanji_master',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(choices=[('n', 'None'), ('h', 'Hiragana'), ('k', 'Katakana')], db_index=True, default='n', max_length=2)),
                ('symbol', models.CharField(max_length=5)),
                ('romaji', models.CharField(blank=True, max_length=20, null=True)),
                ('example_word', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=manabhi_dojo.languages.models.character_audio_upload_path)),
                ('script_type', models.CharField(choices=[('nn', 'Characters'), ('da', 'Dakuten Characters'), ('ha', 'Han-Dakuten Characters'), ('yo', 'Yoon Characters')], db_index=True, default='nn')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('script', 'order')},
            },
        ),
    ]
