# Generated by Django 5.1.7 on 2025-04-07 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quiz_options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='example_word',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='romaji',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='jlpt_level',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kunyomi',
            field=models.CharField(blank=True, default=datetime.datetime(2025, 4, 7, 18, 18, 51, 526170, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanji',
            name='onyomi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
