# Generated by Django 5.1.7 on 2025-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kanji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=5, unique=True)),
                ("onyomi", models.CharField(blank=True, max_length=100, null=True)),
                ("kunyomi", models.CharField(blank=True, max_length=100, null=True)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("jlpt_level", models.CharField(blank=True, max_length=10, null=True)),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("stroke_count", models.IntegerField(blank=True, null=True)),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="kanji_audio/"),
                ),
            ],
            options={
                "db_table": "kanji_master",
            },
        ),
    ]
