# Generated by Django 5.1.7 on 2025-04-11 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_character_quiz_options_alter_character_example_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(choices=[('n', 'None'), ('h', 'Hiragana'), ('k', 'Katakana')], db_index=True, default='n', max_length=2)),
                ('word', models.CharField(blank=True, db_index=True, max_length=50)),
                ('romaji', models.CharField(blank=True, db_index=True, max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='vocab/')),
                ('img_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='kanji',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kanji',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
