# Generated by Django 5.1.7 on 2025-03-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0002_kanji"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
