# Generated by Django 5.1.7 on 2025-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_character_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagescript',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
